version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: laravel-auth-mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
    container_name: laravel-auth-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - cache:/var/www/html/bootstrap/cache
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      APP_ENV: local
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: laravel-auth-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: unless-stopped

volumes:
  mysql-data:
  vendor:
  cache:
